export const icons = {
  backGround: require('./images/backGround.png'),
  ic_leftArrow: require('./images/ic_leftArrow.png'),
  ic_home: require('./images/ic_home.png'),
  ic_logo: require('./images/ic_logo.png'),
  eye_slash: require('./images/eye_slash.webp'),
  eye: require('./images/eye.webp'),
  ic_closeSearch: require('./images/ic_closeSearch.webp'),
  ic_tabSetting: require('./images/tabSetting.webp'),
  ic_tabNotification: require('./images/tabNotification.webp'),
  ic_tabNotification_on: require('./images/tabNotification_on.webp'),
  Menu: require('./images/Menu.webp'),
  avatar: require('./images/avatar.png'),
  ic_ang_pao_featuresHome: require('./images/ic_ang_pao_featuresHome.webp'),
  ic_loan: require('./images/Loan.webp'),
  ic_greatAccount: require('./images/ic_greatAccount.webp'),
  ic_radio: require('./images/Radio.webp'),
  ic_radio_off: require('./images/Radio_off.webp'),
  ic_close: require('./images/Close.webp'),
  ic_personal: require('./images/Personal_Info.webp'),
  ic_unChoose: require('./images/ic_unChoose.webp'),
  ic_choose: require('./images/ic_choose.webp'),
  ic_success: require('./images/Congratz.webp'),
  ic_loyalty: require('./images/ic_loyalty.webp'),
  ic_right: require('./images/ic_right.webp'),
  profile: require('./images/profile.webp'),
  ic_lock: require('./images/lock.webp'),
  ic_exit: require('./images/exit.webp'),
  refresh: require('./images/refresh.webp'),

  //account
  ic_premier: require('./images/premier.webp'),
  vectorDown: require('./images/VectorDown.webp'),
};

export type IconTypes = keyof typeof icons;
